CREATE TABLE IF NOT EXISTS "product_template" (
  "id" serial PRIMARY KEY NOT NULL,
  "template_id" text NOT NULL,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "style_id" integer NOT NULL,
  "leather_id" integer NOT NULL,
  "description_md" text NOT NULL,
  "highlight" text NOT NULL,
  "gallery_images" jsonb NOT NULL,
  "gallery_captions" jsonb NOT NULL,
  "variant_leather_ids" jsonb NOT NULL,
  "sizes" jsonb NOT NULL,
  "craft_process" jsonb NOT NULL,
  "seo" jsonb NOT NULL,
  "category" text NOT NULL,
  "funnel_stage" text NOT NULL,
  "order_reference" jsonb,
  "price_override_grosz" integer,
  CONSTRAINT "product_template_template_id_unique" UNIQUE("template_id"),
  CONSTRAINT "product_template_slug_unique" UNIQUE("slug"),
  CONSTRAINT "product_template_style_id_style_id_fk" FOREIGN KEY ("style_id") REFERENCES "style"("id") ON DELETE CASCADE,
  CONSTRAINT "product_template_leather_id_leather_id_fk" FOREIGN KEY ("leather_id") REFERENCES "leather"("id") ON DELETE CASCADE
);
